version: '3.7'
services:
  api:
    #image: reg-api:latest
    volumes:
      - ./reg_cache/course:/src/moomdate/reg-api/reg_cache/course
      - ./reg_cache/digCode:/src/moomdate/reg-api/reg_cache/digCode
      - ./reg_cache/majorCourse:/src/moomdate/reg-api/reg_cache/majorCourse
    build:
      context: .
      args:
        app_env: production

    image: reg-api
    ports:
      - '8081:8081'
    #sudo docker run -d -i -t -p 8081:8081 c586
