version: '3.7'
services:
  api:
    #image: reg-api:latest
    build:
      context: .
      args:
        app_env: production

    image: reg-api
    ports:
      - '8081:8081'
    #sudo docker run -d -i -t -p 8081:8081 c586
